name: Build and Push Docker Image (Maven)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Navigate to project directory
        run: cd spring-web-app && ls -la # Verify directory contents

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          # Add settings-path if you have a custom Maven settings.xml
          # settings-path: '${{ github.workspace }}/.github/settings.xml'

      - name: Build with Maven
        working-directory: ./spring-web-app
        run: mvn clean package -DskipTests





      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./spring-web-app
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-web-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-web-app:${{ github.sha }}

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz
          sudo mv oc kubectl /usr/local/bin

      - name: Login to OpenShift
        run: |
          echo "$OPENSHIFT_TOKEN" | oc login --token=$(cat -) --server="$OPENSHIFT_SERVER"
        env:
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}

      - name: Set new image for deployment
        run: |
          oc set image deployment/spring-web-app spring-web-app=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/spring-web-app:${{ github.sha }} -n akhilkm02-dev

      - name: Force rollout restart
        run: |
          oc rollout restart deployment/spring-web-app -n akhilkm02-dev